# Vexere Ticket Data Analysis

This notebook preprocesses the provided Vexere dataset including cleanning and feature engineering before analyzing this dataset.

Key activities:
- Checking and handling duplicated, missing, abnormal data(s) (if any).
- Exploring data distribution (numeric column vs category column).
- Feature engineering for later analysis.

## Loading data

In [ ]:
import pandas as pd

file_path = '../Data/TrainTicketSales_Dataset.xlsx'

# Load full dataset
df = pd.read_excel(file_path, sheet_name = "Data")
df.head()

,order_id,ticket_id,passenger_id,passenger_gender,passenger_age,ticket_source_name,ticket_status,created_date,departure_date,departure_time,arrival_date,arrival_time,from_to_location,from_to,airline,seat_class,ticket_price,baggage,insurance_fee,discount_amount
0,20205,31268,Xs1fLinPQun+Oy/mD0FlfXMyJD38YlXJfXNbz+qO+5U=,Female,40.0,IOS,Paid,2023-03-01,2023-03-14,17:55:00,2023-03-14,18:55:00,BMV - SGN,Đắk Lắk - Hồ Chí Minh,Ry/OjEDP12vfMWbnat5Mudc3PE4qIK/wwfCkBE5zGlM=,I1_ECO,867760,0,0.0,45000
1,20190,31242,m/auVlEoaGSe2MqR/Lq4CFXJnI8zauNyF/KiFmMgXHs=,Female,40.0,GYL,Paid,2023-03-01,2023-03-02,09:30:00,2023-03-02,10:30:00,BMV - SGN,Đắk Lắk - Hồ Chí Minh,Ry/OjEDP12vfMWbnat5Mudc3PE4qIK/wwfCkBE5zGlM=,Z1_ECO,974280,0,0.0,45000
2,20245,31337,6HvtV2vTqUfNBJ53C4TzvJnb0s74KgcRNuUVS+8jRvU=,Female,48.0,IOS,Paid,2023-03-01,2023-04-10,13:10:00,2023-04-10,14:35:00,HUI - SGN,Thừa Thiên Huế - Hồ Chí Minh,Ry/OjEDP12vfMWbnat5Mudc3PE4qIK/wwfCkBE5zGlM=,J1_ECO,1423080,0,0.0,16000
3,20259,31360,WiK2P31WEd4mckRNVWz0C2aKKRgSrauAG8NdfTLnKjE=,Male,29.0,Android,New,2023-03-01,2023-04-10,13:10:00,2023-04-10,14:35:00,HUI - SGN,Thừa Thiên Huế - Hồ Chí Minh,Ry/OjEDP12vfMWbnat5Mudc3PE4qIK/wwfCkBE5zGlM=,J1_ECO,1067310,0,0.0,45000
4,20255,31355,6HvtV2vTqUfNBJ53C4TzvJnb0s74KgcRNuUVS+8jRvU=,Female,42.0,IOS,Paid,2023-03-01,2023-04-10,13:10:00,2023-04-10,14:35:00,HUI - SGN,Thừa Thiên Huế - Hồ Chí Minh,Ry/OjEDP12vfMWbnat5Mudc3PE4qIK/wwfCkBE5zGlM=,J1_ECO,1067310,0,0.0,24000

In [8]:
num_rows = df.shape[0]
num_cols = df.shape[1]
print('The number of rows: ', num_rows)
print('The number of columns: ', num_cols)

The number of rows:  19096
The number of columns:  20

## Overview of this dataset

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19096 entries, 0 to 19095
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            19096 non-null  int64
 1   ticket_id           19096 non-null  int64
 2   passenger_id        19096 non-null  object
 3   passenger_gender    19083 non-null  object
 4   passenger_age       19091 non-null  float64
 5   ticket_source_name  19096 non-null  object
 6   ticket_status       19096 non-null  object
 7   created_date        19096 non-null  datetime64[ns]
 8   departure_date      19096 non-null  datetime64[ns]
 9   departure_time      19096 non-null  object
 10  arrival_date        19096 non-null  datetime64[ns]
 11  arrival_time        19096 non-null  object
 12  from_to_location    19096 non-null  object
 13  from_to             19096 non-null  object
 14  airline             19096 non-null  object
 15  seat_class          18976 non-null  object
 16  ticket_price        19096 non-null  int64
 17  baggage             19096 non-null  int64
 18  insurance_fee       19096 non-null  float64
 19  discount_amount     19096 non-null  int64
dtypes: datetime64[ns](3), float64(2), int64(5), object(10)
memory usage: 2.9+ MB

### Meaning of each column

In [23]:
meaning_df = pd.read_excel(file_path, sheet_name = "Data Dictionary")
print(meaning_df)

            Field Name               Description
0             order_id               Mã đơn hàng
1            ticket_id                     Mã vé
2         passenger_id   Mã định danh hành khách
3     passenger_gender      Giới tính hành khách
4        passenger_age           Tuổi hành khách
5   ticket_source_name                  Nguồn vé
6        ticket_status             Trạng thái vé
7         created_date               Ngày đặt vé
8       departure_date            Ngày khởi hành
9       departure_time             Giờ khởi hành
10        arrival_date                  Ngày đến
11        arrival_time                   Giờ đến
12    from_to_location  Sân bay đi - sân bay đến
13             from_to   Tuyến đường tỉnh - tỉnh
14             airline        Mã hãng hàng không
15          seat_class                  Hạng ghế
16        ticket_price                    Giá vé
17             baggage          Tiền mua hành lý
18       insurance_fee         Tiền mua bảo hiểm
19     discount_amount                  Giảm giá

### Meaning of each row

- Each line corresponds to information about ticket' orders including ticket information, passenger information, buying time, route information and fees.

- It does not appear that the lines have different meanings.

## Checking and handle duplicated rows (if any)

In [35]:
duplicated_rows = df.duplicated().sum()
if duplicated_rows > 0:
    print("Number of duplicated row(s): ", duplicated_rows)
else:
    print("There are no duplicated rows")

There are no duplicated rows

## Data type

In [38]:
df.dtypes

order_id                       int64
ticket_id                      int64
passenger_id                  object
passenger_gender              object
passenger_age                float64
ticket_source_name            object
ticket_status                 object
created_date          datetime64[ns]
departure_date        datetime64[ns]
departure_time                object
arrival_date          datetime64[ns]
arrival_time                  object
from_to_location              object
from_to                       object
airline                       object
seat_class                    object
ticket_price                   int64
baggage                        int64
insurance_fee                float64
discount_amount                int64
dtype: object

## Data distribution

### For each column with numeric data type, how are the values distributed?

For columns with numeric data types, we calculate:

- Percentage (from 0 to 1) of missing values
- Min value
- Lower quartile value (25th percentile)
- Median value (50th percentile)
- Upper quartile value (75th percentile)
- Max value

The group will save the results to the DataFrame `num_col_info_df`, where:
- Column names are the names of the numeric columns in `df`
- Row names: “missing_ratio”, “min”, “low_quartile”, “median”, “upper_quartile”, “max”

For ease of viewing, the group rounds all values to 1 decimal place using the `.round(1)` method.

In [71]:
num_col_info_df = None


def missing_values_count(series):
    return series.isna().sum()
    
# Define missing ratio    
def missing_ratio(series):
    percentage = series.isna().sum() / len(series) * 100
    return round(percentage, 1)

# Define lower quartile
def lower_quartile(series):
    return series.quantile(0.25).round(1)

# Define upper quartile
def upper_quartile(series):
    return series.quantile(0.75).round(1)

#Define median
def median(series):
    return series.quantile(0.75).round(1)

num_col_info_df = df.select_dtypes(include=['int64', 'float64'])

num_col_info_df = num_col_info_df.agg([missing_values_count, missing_ratio, "min", lower_quartile, median, upper_quartile, "max"])

num_col_info_df

,order_id,ticket_id,passenger_age,ticket_price,baggage,insurance_fee,discount_amount
missing_values_count,0.0,0.0,0.0,0.0,0.0,0.0,0.0
missing_ratio,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,20142.0,31164.0,0.0,3000.0,0.0,0.0,0.0
lower_quartile,23430.2,36482.2,22.0,737520.0,0.0,0.0,0.0
median,30362.0,47094.8,36.0,1255100.0,0.0,0.0,45000.0
upper_quartile,30362.0,47094.8,36.0,1255100.0,0.0,0.0,45000.0
max,33943.0,52769.0,999999.0,9010800.0,831600.0,60000.0,60000.0

We have 5 missing values in `passenger_age` and some abnormal values (negative values) in `passenger_age`, `baggage`, `insurance_fee` and `discount_amount`

For missing values, since the number is so small (5/19096), we can remove them from the dataset

In [51]:
df.dropna(subset=['passenger_age'], inplace=True)

In [53]:
df['passenger_age'].isna().sum() #Rechecking after cleaning data

0

For abnormal values, we check for the quantity in each column first

In [55]:
cols = ['passenger_age', 'baggage', 'insurance_fee', 'discount_amount']

negative_counts = (df[cols] < 0).sum()

print(negative_counts)

passenger_age      2
baggage            2
insurance_fee      3
discount_amount    2
dtype: int64

The number of abnormal values is also so small, so we can remove them from the dataset

In [59]:
df = df[(df[cols] >= 0).all(axis=1)]

In [61]:
(df[['passenger_age','baggage','insurance_fee','discount_amount']] < 0).sum() #Rechecking after cleaning data

passenger_age      0
baggage            0
insurance_fee      0
discount_amount    0
dtype: int64

### For each column with categorical data type, how are the values distributed?

For columns with the data type `categorical`, we need to calculate:

- The percentage (from 0 to 1) of missing values
- The number of different values (not considering missing values)
- The percentage (from 0 to 100) of each value sorted by decreasing percentage (not considering missing values)

We will save the results to the DataFrame `cat_col_info_df`, where:
- Column names are the non-numeric column names in `df`
- Row names are: “missing_ratio”, “num_values”, “value_ratios”

For ease of viewing, we round all values to 1 decimal place using the `.round(1)` method.

In [67]:
pd.set_option('display.max_colwidth', 100) # For clearly
pd.set_option('display.max_columns', None) # For clearly

In [73]:
cat_col_info_df = df.select_dtypes(include='object')

# Define num values
def num_values(series):
    return len(series.dropna().unique())

# Define value ratios
def value_ratios(series):
    value_counts = series.dropna().value_counts()
    percentages = (value_counts / len(series))*100
    percentages = percentages.round(1)
    sorted_percentages = percentages.sort_values(ascending=False)
    return sorted_percentages.to_dict()
cat_col_info_df = cat_col_info_df.agg([missing_values_count, missing_ratio, num_values, value_ratios])
cat_col_info_df

,passenger_id,passenger_gender,ticket_source_name,ticket_status,departure_time,arrival_time,from_to_location,from_to,airline,seat_class
missing_values_count,0,13,0,0,0,0,0,0,0,120
missing_ratio,0.0,0.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6
num_values,5280,2,3,3,234,243,119,115,4,69
value_ratios,"{'7MHTyxXVgw06aWI7UyjJojbXcNSAZ7IVQKKPA3OC4ZM=': 3.1, 'RtW0BtvvqBXqIzveBR6hh/J9God8PiY3MDszo+vOz...","{'Female': 52.5, 'Male': 47.4}","{'IOS': 64.8, 'Android': 24.6, 'GYL': 10.6}","{'New': 54.5, 'Paid': 44.7, 'Cancel': 0.8}","{08:35:00: 1.8, 21:10:00: 1.5, 18:55:00: 1.4, 06:00:00: 1.4, 17:55:00: 1.4, 05:20:00: 1.3, 08:00...","{07:55:00: 1.9, 14:35:00: 1.8, 09:10:00: 1.5, 07:15:00: 1.5, 23:10:00: 1.5, 20:05:00: 1.4, 18:20...","{'SGN - HAN': 8.2, 'HAN - SGN': 7.2, 'SGN - CXR': 5.4, 'CXR - SGN': 4.8, 'SGN - DAD': 4.5, 'DAD ...","{'Hồ Chí Minh - Hà Nội': 8.2, 'Hà Nội - Hồ Chí Minh': 7.2, 'Hồ Chí Minh - Khánh Hòa': 5.4, 'Khán...","{'Ry/OjEDP12vfMWbnat5Mudc3PE4qIK/wwfCkBE5zGlM=': 65.6, 'V2Ej16fVems7wWmAIxP6MCYYH+i4YSHlvuJgKvD2...","{'E1_ECO': 16.6, 'A1_ECO': 13.9, 'Z1_ECO': 13.7, 'EconomySaver': 8.5, 'W1_ECO': 6.7, 'U1_ECO': 4..."

We have a few missing values in `passenger_gender` and `seat_class`. For these missing values, since the numbers are so small (0.1% and 0.6%), we can remove them from dataset.

In [76]:
df.dropna(subset=['passenger_gender'], inplace=True)

In [78]:
df.dropna(subset=['seat_class'], inplace=True)

In [82]:
#Rechecking after cleaning data
cols = ['passenger_gender',  'seat_class']

null_counts = (df[cols].isnull()).sum()

print(null_counts)

passenger_gender    0
seat_class          0
dtype: int64

## Feature Engineering

We can combine the dates from the departure date column and the corresponding times from the departure time column to form a complete date and time column: `departure_datetime`.

In [85]:
df['departure_datetime'] = pd.to_datetime(
    df['departure_date'].astype(str) + ' ' + df['departure_time'].astype(str)
)

df['arrival_datetime'] = pd.to_datetime(
    df['arrival_date'].astype(str) + ' ' + df['arrival_time'].astype(str)
)

Also add a new column `net_revenue` to calculate the final revenue for each ticket.

In [89]:
df['net_revenue'] = df['ticket_price'] + df['baggage'] + df['insurance_fee'] - df['discount_amount']

Finally, encode `passenger_id` and `airline` for easier viewing.

In [94]:
df['passenger_id'] = 'C-' + (df['passenger_id'].astype('category').cat.codes + 1).astype(str).str.zfill(4)

df['airline'] = 'Airline-' + (df['airline'].astype('category').cat.codes + 1).astype(str).str.zfill(4)

In [97]:
df.head(5)

,order_id,ticket_id,passenger_id,passenger_gender,passenger_age,ticket_source_name,ticket_status,created_date,departure_date,departure_time,arrival_date,arrival_time,from_to_location,from_to,airline,seat_class,ticket_price,baggage,insurance_fee,discount_amount,departure_datetime,arrival_datetime,net_revenue
0,20205,31268,C-2965,Female,40.0,IOS,Paid,2023-03-01,2023-03-14,17:55:00,2023-03-14,18:55:00,BMV - SGN,Đắk Lắk - Hồ Chí Minh,Airline-0002,I1_ECO,867760,0,0.0,45000,2023-03-14 17:55:00,2023-03-14 18:55:00,822760.0
1,20190,31242,C-4138,Female,40.0,GYL,Paid,2023-03-01,2023-03-02,09:30:00,2023-03-02,10:30:00,BMV - SGN,Đắk Lắk - Hồ Chí Minh,Airline-0002,Z1_ECO,974280,0,0.0,45000,2023-03-02 09:30:00,2023-03-02 10:30:00,929280.0
2,20245,31337,C-0694,Female,48.0,IOS,Paid,2023-03-01,2023-04-10,13:10:00,2023-04-10,14:35:00,HUI - SGN,Thừa Thiên Huế - Hồ Chí Minh,Airline-0002,J1_ECO,1423080,0,0.0,16000,2023-04-10 13:10:00,2023-04-10 14:35:00,1407080.0
3,20259,31360,C-2868,Male,29.0,Android,New,2023-03-01,2023-04-10,13:10:00,2023-04-10,14:35:00,HUI - SGN,Thừa Thiên Huế - Hồ Chí Minh,Airline-0002,J1_ECO,1067310,0,0.0,45000,2023-04-10 13:10:00,2023-04-10 14:35:00,1022310.0
4,20255,31355,C-0694,Female,42.0,IOS,Paid,2023-03-01,2023-04-10,13:10:00,2023-04-10,14:35:00,HUI - SGN,Thừa Thiên Huế - Hồ Chí Minh,Airline-0002,J1_ECO,1067310,0,0.0,24000,2023-04-10 13:10:00,2023-04-10 14:35:00,1043310.0

So our data is ok. Now we will save the data after preprocessing.

In [ ]:
save_name = "TrainTicketSales_processed.xlsx"
df.to_excel("../Data/" + save_name, index=False)